// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uojrrowgwlrvnjmmxlvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvanJyb3dnd2xydm5qbW14bHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzEwNjAsImV4cCI6MjA2Nzk0NzA2MH0.8ni_Tmd9WHCZKaOPCmJAW8kWk5z0tuJoD7QChkhAX7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});